### PR TITLE
Add some missing German translations.

### PR DESCRIPTION
**Pull request by Bubu**
Damn you were fast with merging the last one... :-).

### CODE REVIEW

**Comment by javiersantos** [comment]
Hahaha :100:  Could you please add the translation in the [CrowdIn's project page](https://crowdin.com/project/beta-updater-whatsapp) instead of a PR? It's easier for me to manage several translations!

Thanks!

**Comment by Bubu** [comment]
Sure, I'll look into it.

**Comment by Bubu** [comment]
I think I need to be verified as a translator there? Or did I miss a suggestion option that you can then merge (like a PR here)?

**Comment by javiersantos** [comment]
I have just approved your request to join as a translator @Bubu  :+1: 

Thanks!

**Comment by Bubu** [comment]
The crowdin project (for German at least) doesn't seem up to date related to the current Github source xmls. What's up with that?

**Comment by javiersantos** [comment]
You are right. An user sent a PR, but it wasn't uploaded to CrowdIn (and seems it's outdated now).

Feel free to update the translations you want.

**Comment by Bubu** [comment]
I added the translations from this PR in CrowdIn.

**Comment by javiersantos** [comment]
Thanks. I've updated both.

**Pull request closed without merging**
